### ISSUE TITLE
void node pointers are hard to debug

### ISSUE THREAD

**Issue by gh-andre** [neufeldm/akamai-radix-tree#12]
Very useful library. Thank you for maintaining it.

One thing I find quite challenging is to see the contents of radix trees while debugging applications using them. Casting the root node to the actual node type helps with simple trees, but is quite cumbersome, as those templates are very long. After juggling those template names for a bit, I changed my source to get rid of void pointers in the tree, node and children, which made it significantly easier to debug.

You may want to consider changing node pointers to actual types, even if the rest of the code uses void pointers. For example, `RadixTree::root_` would be `typename NodeType::NodeImplType *`, `NodeInterface::nodeImplRef_` would be `NodeImplType*`, `SimpleNodeImpl::children_` would be `std::array<SimpleNodeImpl*,R> children_`, etc. Having these makes debugging easier. 

It would also be nice if allocators have `getPtr` declared the same way - `static` or not, which would make casting the things above more straightforward.

This is just a suggestion. Please feel free to close the issue if there is some reason I'm not seeing you want those to be void pointers.

**Comment by neufeldm** [comment]
Glad you're finding the library useful! I'll take a look at this. Offhand I can't recall why these would have to be void*, but I haven't been in that code for a while.

**Comment by gh-andre** [comment]
Thanks for responding. I'm sure anyone who uses this library will appreciate just being able to click through child nodes and edges in their IDEs :)

**Comment by neufeldm** [comment]
I've taken a look at this, recall why I used void* there, and think I've got a reasonable fix for it. I'm leaving the void* in the allocator - there's a circular dependency between node type and allocator that I don't think I can resolve. I've got an update on the dev/neufeldm branch that I think should do the trick for setting pointer types in the tree and node children if you want to give it a try.

If you're curious about the original motivation for leaving the void* in the tree and node pointers, I had a custom node allocator that was based on a std::vector and used size_t as its reference type. So, I couldn't just have the tree and node use the pointer type without breaking that allocator. I'm not sure what happened to that allocator - I must have pulled it for some reason or another. The fix ought to handle that sort of thing as well as use direct pointers when possible.

**Comment by gh-andre** [comment]
Thank you for looking into this. I just gave it a quick go with simple and binary nodes and it appears to be working - I can see nodes and edges in the debugger on Windows. I am starting another chunk of work tomorrow on Linux and will see how it works out in GDB. Will post an update next week.

Thank you for the details. I gathered from the comments about circular dependency and also left the void pointer in the allocator in my fix, but you also changed `AllocatorNew`, which avoids a bunch of casts and is quite nice. It does leave `AllocatorTraits` specialization for `AllocatorNew` somewhat disconnected from the allocator in the sense that it was synchronized on `void*` in both of them before, but there appears to be no side effects for it.

I can appreciate custom allocators and will be looking much closer into it at a later time. For now I'm just looking for things to minimize allocations, like replacing `std::vector` in `SimplePath` with `std::array` - those are created very often as query keys and reducing allocations there helps. 

Anyway, thanks again for jumping in so quickly on this. It makes my life much easier for not having to maintain my simplistic patch and rather use a thoughtful fix :)

**Comment by neufeldm** [comment]
Cool - also nice to hear that it works on Windows. I've tried to keep it Windows-friendly, but haven't spent as much time on that as on Linux and Mac. For a ```std::array``` version of ```SimplePath``` have you tried just swapping in ```SimpleEdge``` for ```SimplePath```? As I recall the edge/path distinction is pretty blurry - edges wind up mostly being less flexible/more efficient versions of paths, good chance it'd be pretty close to working as-is.

**Comment by neufeldm** [comment]
Your point about disconnecting the allocator traits from the allocator is well taken. I've moved it over to the allocator header, added a few comments. I'll merge the fixes into the master and close the issue unless there's something else needed that you can think of.

**Comment by gh-andre** [comment]
Thank you for your hard work. It is much appreciated, as are the suggestions you mentioned. I will certainly check out edges vs. paths.

Ran a quick check with the latest code on the dev branch and it working well for debugging, so the issue is definitely addressed. Please go ahead and close it.

One last, unrelated, question, if you don't mind. If I use different RO cursor instances to look up values and walk the tree (e.g. go parent, etc), is it thread-safe? I'm assuming the entire tree needs to be locked for writing, given that any node state may be modified on write.

**Comment by neufeldm** [comment]
Read-only is thread safe. As far as writing goes only safe thing is to lock the whole tree.

There are some instances where you could get away with simultaneous read/write, but it'd be heavily dependent on the actual node structure, where the reading and writing is done in the tree, and specific cursors being used. Definitely dicey at best.

**Comment by gh-andre** [comment]
Thank you for confirming thread safety and, once again, for the fix.
